services:
  - type: web
    name: Kfueit-Bus-System
    env: python
    buildCommand: "./build_files.sh"
    startCommand: "gunicorn KfueitBusSystem.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "kfueit-bus-system.onrender.com"
      - key: PYTHON_VERSION
        value: "3.11"
