# Generated by Django 5.0.6 on 2024-09-03 06:43

import BusRoute.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusRoute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=4, null=True, validators=[BusRoute.validators.validate_24_hour_format])),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_points', to='BusRoute.busroute')),
                ('stop_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusRoute.stoppoint')),
            ],
        ),
        migrations.CreateModel(
            name='DropPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, max_length=4, null=True, validators=[BusRoute.validators.validate_24_hour_format])),
                ('bus_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_points', to='BusRoute.busroute')),
                ('stop_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusRoute.stoppoint')),
            ],
        ),
    ]
