# Generated by Django 5.0.6 on 2024-09-03 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusRoute', '0002_busroute_stoppoint_pickuppoint_droppoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('date_lost', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='missing_items/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('found', 'Found'), ('not_found', 'Not Found')], default='pending', max_length=10)),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
