# Generated by Django 5.0.6 on 2024-09-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusRoute', '0004_busdriver_driverreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverreview',
            name='image',
            field=models.ImageField(upload_to='driver_images/'),
        ),
    ]
