# Generated by Django 5.0.6 on 2024-09-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BusRoute', '0005_alter_driverreview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverreview',
            name='image',
        ),
        migrations.AddField(
            model_name='busdriver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images/'),
        ),
    ]
